{% set name = "asyncpgsa" %}
{% set version = "0.25.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8c835271a7f15f7f47fb2c6c1fb3a1bcc6d738133ad330cfd219e92f71a78001" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
    # Project imports itself to find out version during build
    # time which results into importing runtime dependencies
    - asyncpg
    - sqlalchemy
  run:
    - python
    - asyncpg
    - sqlalchemy

test:
  imports:
    - asyncpgsa
    - asyncpgsa.testing

about:
  home: https://github.com/canopytax/asyncpgsa
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: A fast PostgreSQL Database Client Library for Python/asyncio.
  description: |
    asyncpgsa is a database interface library designed specifically for
    PostgreSQL and Python/asyncio. asyncpgsa is an efficient, clean
    implementation of PostgreSQL server binary protocol for use with Python's
    asyncio framework.
  dev_url: https://github.com/CanopyTax/asyncpgsa
  doc_url: http://asyncpgsa.readthedocs.io
  doc_source_url: https://github.com/CanopyTax/asyncpgsa/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - nehaljwani
