appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eOXxQeAbs3z9Oxs1mA3E778wO5fIklZLhe9GSLvxFSX4Ql8SRHg+IEwbOckRxGPhqB5lhe44dePgjTv6M5Cr+PCbdtsF7QUqkMYLkHYsaU3hIg4mjPs0FBK/o4NNYjvq7Vn1b7VfUpETHnUJd54pPEPHWXHlU+I8l2a67aLgv2bJPmLSz+wtpZVmXKwyVtwnKG1D9N+vpte2tSEzBsq95FaEh7UIAbQqYqRF6ocAi33dn9P9mKXgAUJHxJEARcpOjBG/GcGtII5IriK+9mFIp364+90EznHS54x/YvL8pziMTcVKlrGRb9WGqLb0y64NBxW3UmfP8sGhaOghEdYmnKx3A3V3zOoN8FeDleXxY5KFco02cfMwFJs1tWI1zq0D3Wiw3CsiHTejRVGp8SDOn/NPlvv9XczZdgO83RJguvaqgLD+8hQZ7/KY+NCYX6Q5a/DjRw85C/YmokyJjKr9HEcvmEA2PBsdZLKv9DpjJ2CBVCGG0OVMvp6AaV86Ww0OhzpUOlQCppaw0Qv89KbVh4IkHo7QiKZK1OikFT0/8GuUV5jId/xXFL872wu0Ay7Zaj9KncQUsc6h9pt+p7nJXKvTEIT1EZIjXVsG6EiSCu6iEtUDUBugCbgRd9oNooqGjKGsrjyiErRs+XKHWlCUmr/enma4cCHNWcclFdBt2Hg=}
provider:
  win: azure
conda_forge_output_validation: true
